version: "3.9"

services:
  postgres-order:
    image: postgres:15
    container_name: postgres-order
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: orderdb
    volumes:
      - orderdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orderdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build: .
    container_name: order-service
    restart: always
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: postgresql://postgres:admin123@postgres-order:5432/orderdb

      JWT_SECRET: supersecret

      PRODUCT_SERVICE_URL: http://product-service:3003
      SHIPPING_SERVICE_URL: http://shipping-service:3006

      WHATSAPP_API_URL: https://your-whatsapp-api/send
      ADMIN_PHONE: 2348012345678

      APP_URL: http://localhost:3000

      PAYSTACK_SECRET: your_paystack_secret
      FLW_SECRET: your_flutterwave_secret

    depends_on:
      postgres-order:
        condition: service_healthy

volumes:
  orderdb-data: